### ISSUE TITLE
What is the purpose of the  "A method can't be added" rule?

### ISSUE THREAD

**Issue by qm3ster** [bcherny/india#5]
Why is adding a method more than a patch change?
It can't break existing calls.

**Comment by bcherny** [comment]
See the definition of a minor change: http://semver.org

**Comment by qm3ster** [comment]
Thank you, I see it is to adhere to the specification.
Do you know the reason it is singled out in such a way?

**Comment by bcherny** [comment]
With semver there are 3 types of changes-
- **Major changes** that break existing functionality, often to add features
- **Minor changes** that add features without breaking functionality
- **Patch changes** that do not add or remove features, and are for bug fixes

It's just a convention, there's no reason these 3 categories are special. In practice, it ends up being a good way to classify the types of changes that real projects make.
